config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('data.urls')),
    path('', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from .views import (
    NewsDetailView,
    NewsListView
)

app_name = 'content'

urlpatterns = [
    path('news/<pk>', NewsDetailView.as_view(), name='snews'),  # single news
    path('news', NewsListView.as_view(), name='news')
]

data/urls.py
from django.urls import path

from .views import (
    ReportCardDetailView,
    ReportCards
)


app_name = 'data'

urlpatterns = [
    path('report-card', ReportCards.as_view(), name='rcards'),
    path('report-card/<str:year>', ReportCardDetailView.as_view(), name='rcard_detail')
]

data/models.py
from multiprocessing import Manager
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from account.models import User

# Create your models here.


class Lesson(models.Model):
    name = models.CharField(
    max_length=25,
    verbose_name='نام',
    null=False, blank=False
    )

    class Meta:
        verbose_name = 'درس'
        verbose_name_plural = 'دروس'
    
    def __str__(self):
        return self.name


class Class(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='نام',
        unique=True
        )
    students = models.ForeignKey(
        User,
        verbose_name='دانش آموزان',
        null=True, blank=True,
        on_delete=models.DO_NOTHING,
        related_name='students', 
        related_query_name='student'
    )
    teacher = models.ManyToManyField(
        User,
        verbose_name='معلمین',
        related_name='teachers',
        related_query_name='teacher'
    )

    class Meta:
        verbose_name = 'کلاس'
        verbose_name_plural = 'کلاس ها'


class Grade(models.Model):
    name = models.CharField(
        max_length=50,
        verbose_name='نام'
    )
    classes = models.ForeignKey(
        Class,
        verbose_name='کلاس ها',
        on_delete=models.DO_NOTHING,
        # related_name='classes'
    )
    lessons = models.ForeignKey(
        Lesson,
        verbose_name='دروس',
        on_delete=models.DO_NOTHING,
        # related_name='lessons'
    )
    students = models.ForeignKey(
        User,
        verbose_name='دانش آموزان',
        on_delete=models.DO_NOTHING,
        # related_name='students'
    )

    class Meta:
        verbose_name = 'پایه'
        verbose_name_plural = 'پایه ها'
    
    def __str__(self):
        return self.name


class ReportCard(models.Model):
    student = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        verbose_name='دانش آموز'
    )
    year = models.CharField(
        verbose_name='سال تحصیلی',
        max_length=10
    )

    class Meta:
        verbose_name = 'کارنامه'
        verbose_name_plural = 'کارنامه ها'
    
    def __str__(self):
        return f'{self.student.full_name()} | {self.year}'


class Score(models.Model):
    quarter1 = models.FloatField(
        verbose_name='میان ترم اول',
        default=0.0,
        validators=[
            MinValueValidator(0.0), MaxValueValidator(20.0)
        ]
    )
    quarter2 = models.FloatField(
        verbose_name='ترم اول',
        default=0.0,
        validators=[
            MinValueValidator(0.0), MaxValueValidator(20.0)
        ]
    )
    quarter3 = models.FloatField(
        verbose_name='میان ترم دوم',
        default=0.0,
        validators=[
            MinValueValidator(0.0), MaxValueValidator(20.0)
        ]
    )
    quarter4 = models.FloatField(
        verbose_name='خرداد',
        default=0.0,
        validators=[
            MinValueValidator(0.0), MaxValueValidator(20.0)
        ]
    )
    lesson = models.ForeignKey(
        Lesson,
        verbose_name='نام درس', 
        on_delete=models.PROTECT
    )
    rcard = models.ForeignKey(
        ReportCard,
        verbose_name='کارنامه',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = 'نمره درس'
        verbose_name_plural = 'نمرات دروس'
    
    def __str__(self):
        return f'{self.rcard.student.full_name()} | {self.lesson}'

data/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import (
    ReportCard
)

# Create your views here.


class ReportCards(LoginRequiredMixin, View):
    def get(self, request):
        userid = request.user.id
        rcards = ReportCard.objects.filter(student_id=userid)
        context = {
            'rcards': rcards
        }
        return render(request, 'data/ReportCards.html', context)


class ReportCardDetailView(LoginRequiredMixin, DetailView):
    def get_object(self):
        rcard_year = self.kwargs.get('year')
        user = self.request.user.id
        rcard = get_object_or_404(ReportCard, student_id=user, year=rcard_year)
        return rcard
    template_name = 'data/ReportCard.html'
    context_object_name = 'rcard'
    

data/templates/data/ReportCard.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>کارنامه</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap4.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  
  <!-- bootstrap rtl -->
  <link rel="stylesheet" href="{% static 'dist/css/bootstrap-rtl.min.css' %}">
  <!-- template rtl version -->
  <link rel="stylesheet" href="{% static 'dist/css/custom-style.css' %}">
{% endblock head %}

{% block body %}
  <body class="sidebar-mini" style="height: auto;">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
          <a href="/" class="nav-link">خانه</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'content:news' %}" class="nav-link">اخبار</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'data:rcards' %}" class="nav-link">کارنامه ها</a>
        </li> 
      </ul>
    </nav>

    <div>
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h4>کارنامه {{ rcard.student.full_name }} {{ rcard.year }}</h4>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                <li class="breadcrumb-item"><a href="{% url 'data:rcards' %}">کارنامه ها</a></li>
                <li class="breadcrumb-item active">{{ rcard.student.full_name }} {{ rcard.year }}</li>

              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      <section>
        <div class="row">
          <div class="col-12">
            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid">
                  <thead>
                  <tr role="row"><th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="موتور رندر: activate to sort column descending">نام درس</th><th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="مرورگر: activate to sort column ascending">میان ترم اول</th><th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="سیستم عامل: activate to sort column ascending">ترم اول</th><th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="ورژن: activate to sort column ascending">میان ترم دوم</th><th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="امتیاز: activate to sort column ascending">ترم دوم</th></tr>
                  </thead>
                  <tbody>
                    {% for i in rcard.score_set.all %}

                    <td class="sorting_1">{{ i.lesson.name }}</td>
                    <td>{{ i.quarter1 }}</td>
                    <td>{{ i.quarter2 }}</td>
                    <td>{{ i.quarter3 }}</td>
                    <td>{{ i.quarter4 }}</td>
                    {% endfor %}
                  </tbody> 
                  <tfoot>
                  <tr><th rowspan="1" colspan="1">نام درس</th><th rowspan="1" colspan="1">میان ترم اول</th><th rowspan="1" colspan="1">ترم اول</th><th rowspan="1" colspan="1">میان ترم دوم</th><th rowspan="1" colspan="1">ترم دوم</th></tr>
                  </tfoot>
              </div>
              <!-- /.card-body -->
            </div>
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- ./wrapper -->
  {% include 'footer.html' %}
  </body>
{% endblock body %}

data/templates/data/ReportCards.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>پنل مدیریت | ویجت‌ها</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- bootstrap rtl -->
  <link rel="stylesheet" href="{% static 'dist/css/bootstrap-rtl.min.css' %}">
  <!-- template rtl version -->
  <link rel="stylesheet" href="{% static 'dist/css/custom-style.css' %}">

{% endblock head %}


{% block body %}
<body class="sidebar-mini control-sidebar-slide-open" style="height: auto;">
    <div class="wrapper">
      <!-- Navbar -->
      <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">خانه</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'content:news' %}" class="nav-link">اخبار</a>
          </li>
        </ul>
      </nav>
      <!-- /.navbar -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper" style="margin-right:80px !important; background-color: #fff;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>ویجت‌ها</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                  <li class="breadcrumb-item"><a href="#">خانه</a></li>
                  <li class="breadcrumb-item active">کارنامه ها</li>
                </ol>
              </div>
            </div>
          </div><!-- /.container-fluid -->
        </section>
    
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <!-- =========================================================== -->
            <h5 class="mt-4 mb-2"></h5>
            <div class="row">            
            {% for card in rcards %}
                <div class="col-md-3 col-sm-6 col-12">
                  <a href="{% url 'data:rcard_detail' card.year %}">
                    <div class="info-box bg-info">
                      <span class="info-box-icon"><i class="ion ion-stats-bars"></i></span>
        
                      <div class="info-box-content">
                        <span class="info-box-text">{{ card }}</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </a>
                </div>
            {% endfor %}      
            </div>

          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->  
    </div>
    <!-- ./wrapper -->
    
    </body>
{% endblock body %}