account/urls.py
from django.urls import path

from .views import (
    SignInView
)

app_name = 'account'

urlpatterns = [
    path('login', SignInView.as_view(), name='login')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('data.urls')),
    path('', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from .views import (
    NewsDetailView,
    NewsListView
)

app_name = 'content'

urlpatterns = [
    path('news/<pk>', NewsDetailView.as_view(), name='snews'),  # single news
    path('news', NewsListView.as_view(), name='news')
]

data/urls.py
from django.urls import path

from .views import (
    ReportCardDetailView,
    ReportCards
)


app_name = 'data'

urlpatterns = [
    path('report-card', ReportCards.as_view(), name='rcards'),
    path('report-card/<str:year>', ReportCardDetailView.as_view(), name='rcard_detail')
]

content/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

# Create your models here.


class News(models.Model):
    banner = models.ImageField(
        upload_to='media/news/', max_length='200', default='media/defaults/news_banner.jpg'
    )
    title = models.CharField(
        verbose_name='تایل', max_length=50
    )
    text = RichTextUploadingField(
        null=True, blank=True
    )
    date_added = models.DateTimeField(
        verbose_name='تاریخ اضافه شدن', default=timezone.now
    )
    to_other_pages = models.BooleanField(
        default=True
    )

    class Meta:
        verbose_name = 'خبر'
        verbose_name_plural = 'اخبار'

    def __str__(self):
        return f'{self.title} | {self.date_added}'

content/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import News

# Create your views here.


class NewsDetailView(DetailView):
    model = News
    template_name = "content/News.html"
    context_object_name = 'news'


class NewsListView(ListView):
    model = News
    queryset = News.objects.all().order_by('date_added')
    context_object_name = 'news'
    template_name = 'content/NewsList.html'

content/templates/content/News.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>خانه</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- bootstrap rtl -->
  <link rel="stylesheet" href="{% static 'dist/css/bootstrap-rtl.min.css' %}">
  <!-- template rtl version -->
  <link rel="stylesheet" href="{% static 'dist/css/custom-style.css' %}">
{% endblock head %}

{% block body %}
<body class="sidebar-mini control-sidebar-slide-open" style="height: auto;">
  
<style>
  .test {
    border: 1px solid #121212;
    border-radius: 5px
  }
</style>

  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
          <a href="/" class="nav-link">خانه</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'content:news' %}" class="nav-link">اخبار</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'account:login' %}" class="nav-link">ورود</a>
        </li>
        {% else %} 
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'data:rcards' %}" class="nav-link">کارنامه ها</a>
        </li> 
        {% endif %}
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="margin-right:80px !important">
      <!-- Content Header (Page header) -->
      <section class="content-header" style="background-color: #fff !important; padding-right: 118.5px !important">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-12">
              <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                <li class="breadcrumb-item"><a href="{% url 'content:news' %}">اخبار</a></li>
                <li class="breadcrumb-item active">{{ news.title }}</li>
              </ol>
            </div>
            <div class="col-sm-10 test">
              <img class="nbanner col-sm-12" src="/{{ news.banner }}">
              <br>
              <br>
              <h1>{{ news.title }}</h1>
              <br>
              <div class="center">
                {{ news.text|safe }}
              </div>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- =========================================================== -->
          <h5 class="mt-4 mb-2"></h5>

        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->  
  </div>
  <!-- ./wrapper -->
  {% include 'footer.html' %}
</body>
{% endblock body %} 

content/templates/content/NewsList.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>خانه</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <!-- bootstrap rtl -->
  <link rel="stylesheet" href="{% static 'dist/css/bootstrap-rtl.min.css' %}">
  <!-- template rtl version -->
  <link rel="stylesheet" href="{% static 'dist/css/custom-style.css' %}">
{% endblock head %}

{% block body %}

<style>
  .article-card {
    overflow: hidden;
    position: relative;
    height: 140px;
    border: 2.5px solid #fff;
  }
    
  .test {
    border: 1.5px solid #03fcec;
    border-radius: 10px;
    height: 100px;
    box-shadow: 2px 2px 4px #017069;
    background-size: 375px;
    width: 375px;
    height: 115px;
    border: 2px solid;
  }
  
</style>

<body class="sidebar-mini control-sidebar-slide-open" style="height: auto;">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
          <a href="/" class="nav-link">خانه</a>
        </li>
        {% if request.user.is_anonymous %}
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'account:login' %}" class="nav-link">ورود</a>
        </li>
        {% else %} 
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'data:rcards' %}" class="nav-link">کارنامه ها</a>
        </li> 
        {% endif %}
      </ul>
    
      <!-- Right navbar links -->
      <ul class="navbar-nav mr-auto">
        <!-- Messages Dropdown Menu -->
        {% comment %} TODO: School logo {% endcomment %}
      </ul>
    </nav>
    <!-- /.navbar -->
  
    <!-- Main Sidebar Container -->
    
  
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="margin-right:80px !important">
      <!-- Content Header (Page header) -->
      <section class="content-header" style="background-color: #fff !important;">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-12">
              <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item"><a href="/">خانه</a></li>
                <li class="breadcrumb-item active">اخبار</li>
              </ol>
            </div>
            <div class="col-sm-10">
              <h1>اخبار</h1>
              <br>
            </div>
            {% for article in news %}
            <article class="col-md-4 article-card">
              {% comment %} <img src="{{ article.banner }}"> {% endcomment %}
              <a href="{% url 'content:snews' article.pk %}">
              <div class='test' style="background-image:url('{{ article.banner }}')">
                  <h2 class="text-center">{{ article.title }}</h2>
                  {% comment %} <img class="img-responsive filterdark" width="375" height="175" sizes="(max-width: 768px) 200px, 264px" src="{{ article.banner }}" > {% endcomment %}
              </div>
            </a>
          </article>
          {% endfor %}
            
          </div>
        </div><!-- /.container-fluid -->
      </section>
  
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- =========================================================== -->
          <h5 class="mt-4 mb-2"></h5>

        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->  
  </div>
  <!-- ./wrapper -->
  {% include 'footer.html' %}
</body>
{% endblock body %} 